---

variables:
  BUILD_IMAGE: "maven:3.6.3-jdk-8"
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2"
  BUILD_GOAL: "install -DskipTests"
  
stages:
  - build
  
.build_template: &build_template
  only:
    - master
  image: $BUILD_IMAGE
  stage: build
  script:
    - |
      mkdir -p ~/.m2/
      if [ -f .m2.settings.xml ]; then
        cp .m2.settings.xml ~/.m2/settings.xml
      fi
      mvn -f ./springboot-backend/ $BUILD_GOAL
  
build:
  <<: *build_template
  